In [1]:
import numpy as np

### 행렬 차원을 변경

In [2]:
# 1차원 행렬을 생성한다.
array1 = np.arange(15)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
# 1차원 -> 2차원
array2 = array1.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
# 2차원 -> 1차원
# reshape 함수 안에 전체 원소의 개수를 넣어줘야 하지만
# -1 을 넣어주면 알아서 처리해준다.
array3 = array2.reshape(-1)
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])